name: Run Cirrus Tasks

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  cirrus:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cirruslabs/cirrus-action@v2
